ALTER TABLE public.comment_likes ADD CONSTRAINT comment_likes_pkey PRIMARY KEY (id);
ALTER TABLE public.comment_likes ADD CONSTRAINT comment_likes_user_id_comment_id_key UNIQUE (user_id, comment_id);
ALTER TABLE public.comment_likes ADD CONSTRAINT comment_likes_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE;
ALTER TABLE public.comment_likes ADD CONSTRAINT comment_likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.comments ADD CONSTRAINT comments_pkey PRIMARY KEY (id);
ALTER TABLE public.comments ADD CONSTRAINT comments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES comments(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.comments ADD CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.comments ADD CONSTRAINT comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE;
ALTER TABLE public.dev_blog ADD CONSTRAINT dev_blog_pkey PRIMARY KEY (id);
ALTER TABLE public.dev_blog ADD CONSTRAINT dev_blog_slug_key UNIQUE (slug);
ALTER TABLE public.dev_blog ADD CONSTRAINT dev_blog_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.follows ADD CONSTRAINT follows_pkey PRIMARY KEY (id);
ALTER TABLE public.follows ADD CONSTRAINT follows_following_id_fkey FOREIGN KEY (following_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.follows ADD CONSTRAINT follows_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.likes ADD CONSTRAINT likes_pkey PRIMARY KEY (id);
ALTER TABLE public.likes ADD CONSTRAINT likes_user_post_unique UNIQUE (user_id, post_id);
ALTER TABLE public.likes ADD CONSTRAINT likes_post_id_fkey FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE;
ALTER TABLE public.likes ADD CONSTRAINT likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.movie_genre_stats ADD CONSTRAINT movie_genre_stats_pkey PRIMARY KEY (id);
ALTER TABLE public.movie_genre_stats ADD CONSTRAINT movie_genre_stats_user_id_unique UNIQUE (user_id);
ALTER TABLE public.movie_genre_stats ADD CONSTRAINT movie_genre_stats_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.new_episodes ADD CONSTRAINT new_episodes_pkey PRIMARY KEY (id);
ALTER TABLE public.new_episodes ADD CONSTRAINT new_episodes_user_tv_unique UNIQUE (user_id, tv_id);
ALTER TABLE public.new_episodes ADD CONSTRAINT new_episodes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
ALTER TABLE public.notifications ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);
ALTER TABLE public.notifications ADD CONSTRAINT notifications_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.notifications ADD CONSTRAINT notifications_triggered_by_fkey FOREIGN KEY (triggered_by) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.notifications ADD CONSTRAINT notifications_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES comments(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.notifications ADD CONSTRAINT notifications_post_id_fkey FOREIGN KEY (post_id) REFERENCES posts(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.posts ADD CONSTRAINT posts_pkey PRIMARY KEY (id);
ALTER TABLE public.posts ADD CONSTRAINT posts_creatorid_fkey FOREIGN KEY (creatorid) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.saves ADD CONSTRAINT saves_pkey PRIMARY KEY (id);
ALTER TABLE public.saves ADD CONSTRAINT saves_user_post_unique UNIQUE (user_id, post_id);
ALTER TABLE public.saves ADD CONSTRAINT saves_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.saves ADD CONSTRAINT saves_post_id_fkey FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE;
ALTER TABLE public.tv_genre_stats ADD CONSTRAINT tv_genre_stats_pkey PRIMARY KEY (id);
ALTER TABLE public.tv_genre_stats ADD CONSTRAINT tv_genre_stats_user_id_unique UNIQUE (user_id);
ALTER TABLE public.tv_genre_stats ADD CONSTRAINT tv_genre_stats_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.user_ip_addresses ADD CONSTRAINT user_ip_addresses_pkey PRIMARY KEY (id);
ALTER TABLE public.user_ip_addresses ADD CONSTRAINT fk_user_ip_addresses_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.user_jellyfin_config ADD CONSTRAINT user_jellyfin_config_pkey PRIMARY KEY (id);
ALTER TABLE public.user_jellyfin_config ADD CONSTRAINT user_jellyfin_config_user_id_key UNIQUE (user_id);
ALTER TABLE public.user_jellyfin_config ADD CONSTRAINT user_jellyfin_config_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE public.users ADD CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id);
ALTER TABLE public.watch_history ADD CONSTRAINT watch_history_pkey PRIMARY KEY (id);
ALTER TABLE public.watch_history ADD CONSTRAINT watch_history_unique UNIQUE (user_id, media_type, media_id, season_number, episode_number);
ALTER TABLE public.watch_history ADD CONSTRAINT watch_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.watch_list ADD CONSTRAINT watch_list_pkey PRIMARY KEY (id);
ALTER TABLE public.watch_list ADD CONSTRAINT watch_list_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE;
