CREATE INDEX comment_likes_comment_id_idx ON public.comment_likes USING btree (comment_id);
CREATE UNIQUE INDEX comment_likes_pkey ON public.comment_likes USING btree (id);
CREATE UNIQUE INDEX comment_likes_user_id_comment_id_key ON public.comment_likes USING btree (user_id, comment_id);
CREATE INDEX comment_likes_user_id_idx ON public.comment_likes USING btree (user_id);
CREATE INDEX comments_parent_id_idx ON public.comments USING btree (parent_id);
CREATE UNIQUE INDEX comments_pkey ON public.comments USING btree (id);
CREATE INDEX comments_post_id_idx ON public.comments USING btree (post_id);
CREATE INDEX comments_user_id_idx ON public.comments USING btree (user_id);
CREATE INDEX idx_comments_parent_id ON public.comments USING btree (parent_id) WHERE (parent_id IS NOT NULL);
CREATE INDEX idx_comments_post_id ON public.comments USING btree (post_id);
CREATE UNIQUE INDEX dev_blog_pkey ON public.dev_blog USING btree (id);
CREATE UNIQUE INDEX dev_blog_slug_key ON public.dev_blog USING btree (slug);
CREATE INDEX follows_following_id_idx ON public.follows USING btree (following_id);
CREATE UNIQUE INDEX follows_pkey ON public.follows USING btree (id);
CREATE INDEX follows_user_id_idx ON public.follows USING btree (user_id);
CREATE INDEX idx_follows_following_id ON public.follows USING btree (following_id);
CREATE INDEX idx_follows_user_id ON public.follows USING btree (user_id);
CREATE UNIQUE INDEX likes_pkey ON public.likes USING btree (id);
CREATE INDEX likes_post_id_idx ON public.likes USING btree (post_id);
CREATE INDEX likes_user_id_idx ON public.likes USING btree (user_id);
CREATE UNIQUE INDEX likes_user_post_unique ON public.likes USING btree (user_id, post_id);
CREATE UNIQUE INDEX movie_genre_stats_pkey ON public.movie_genre_stats USING btree (id);
CREATE INDEX movie_genre_stats_user_id_idx ON public.movie_genre_stats USING btree (user_id);
CREATE UNIQUE INDEX movie_genre_stats_user_id_unique ON public.movie_genre_stats USING btree (user_id);
CREATE INDEX idx_new_episodes_user_airdate ON public.new_episodes USING btree (user_id, last_air_date DESC);
CREATE UNIQUE INDEX new_episodes_pkey ON public.new_episodes USING btree (id);
CREATE UNIQUE INDEX new_episodes_user_tv_unique ON public.new_episodes USING btree (user_id, tv_id);
CREATE UNIQUE INDEX notifications_pkey ON public.notifications USING btree (id);
CREATE INDEX idx_posts_creatorid ON public.posts USING btree (creatorid);
CREATE INDEX idx_posts_media_lookup ON public.posts USING btree (media_type, media_id);
CREATE INDEX posts_creatorid_idx ON public.posts USING btree (creatorid);
CREATE INDEX posts_creatorid_media_type_idx ON public.posts USING btree (creatorid, media_type);
CREATE INDEX posts_id_idx ON public.posts USING btree (id);
CREATE UNIQUE INDEX posts_pkey ON public.posts USING btree (id);
CREATE INDEX posts_total_comments_idx ON public.posts USING btree (total_comments);
CREATE INDEX posts_total_likes_idx ON public.posts USING btree (total_likes);
CREATE UNIQUE INDEX saves_pkey ON public.saves USING btree (id);
CREATE INDEX saves_post_id_idx ON public.saves USING btree (post_id);
CREATE INDEX saves_user_id_idx ON public.saves USING btree (user_id);
CREATE UNIQUE INDEX saves_user_post_unique ON public.saves USING btree (user_id, post_id);
CREATE UNIQUE INDEX tv_genre_stats_pkey ON public.tv_genre_stats USING btree (id);
CREATE INDEX tv_genre_stats_user_id_idx ON public.tv_genre_stats USING btree (user_id);
CREATE UNIQUE INDEX tv_genre_stats_user_id_unique ON public.tv_genre_stats USING btree (user_id);
CREATE INDEX idx_user_ip_addresses_ip ON public.user_ip_addresses USING btree (ip_address);
CREATE INDEX idx_user_ip_addresses_user_id ON public.user_ip_addresses USING btree (user_id);
CREATE UNIQUE INDEX user_ip_addresses_pkey ON public.user_ip_addresses USING btree (id);
CREATE UNIQUE INDEX user_jellyfin_config_pkey ON public.user_jellyfin_config USING btree (id);
CREATE UNIQUE INDEX user_jellyfin_config_user_id_key ON public.user_jellyfin_config USING btree (user_id);
CREATE INDEX users_id_idx ON public.users USING btree (id);
CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);
CREATE INDEX idx_watch_history_batch_lookup ON public.watch_history USING btree (user_id, media_type, media_id) WHERE (media_type = ANY (ARRAY['movie'::text, 'tv'::text]));
CREATE INDEX idx_watch_history_next_episodes ON public.watch_history USING btree (user_id, media_id, season_number DESC, episode_number DESC) WHERE (hidden_until IS NULL);
CREATE INDEX idx_watch_history_not_hidden ON public.watch_history USING btree (user_id, hidden_until) WHERE (hidden_until IS NULL);
CREATE INDEX idx_watch_history_user_created_desc ON public.watch_history USING btree (user_id, created_at DESC);
CREATE INDEX idx_watch_history_user_media_lookup ON public.watch_history USING btree (user_id, media_type, media_id, season_number, episode_number);
CREATE UNIQUE INDEX watch_history_pkey ON public.watch_history USING btree (id);
CREATE UNIQUE INDEX watch_history_unique ON public.watch_history USING btree (user_id, media_type, media_id, season_number, episode_number);
CREATE INDEX watch_history_user_id_idx ON public.watch_history USING btree (user_id);
CREATE INDEX watch_history_user_id_media_type_media_id_season_number_epi_idx ON public.watch_history USING btree (user_id, media_type, media_id, season_number, episode_number);
CREATE UNIQUE INDEX watch_list_pkey ON public.watch_list USING btree (id);
CREATE INDEX watch_list_user_id_media_type_media_id_watch_list_type_idx ON public.watch_list USING btree (user_id, media_type, media_id, watch_list_type);
